databases:
  - name: hosannapointdb
    databaseName: hosannapointdb
    user: hosannapointdb_user

services:
  - type: web
    name: hosanaPosBackendAPI
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hosannapointdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false