# PostgreSQL. Versions 9.3 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%=ENV['DATABASE_DEV']%>
  username: <%=ENV['USERNAME']%>
  password: <%=ENV['PASSWORD']%>

test:
  <<: *default
  database: <%=ENV['DATABASE_TEST']%>
  username: <%=ENV['USERNAME']%>
  password: <%=ENV['PASSWORD']%>

# production:
#   <<: *default
#   database: hozsystem_production
#   username: gra
#   password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>